[package]
name = "rust_rs"
version = "0.1.0"
authors = ["sandy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
scraper = "0.11.0"
select = "*"
